### ISSUE TITLE
Can't push a "Zero" as int

### ISSUE THREAD

**Issue by cbitterfield** [Locoduino/RingBuffer#12]
Can't push value into the buffer as a "ZERO"

```
#define ZERO 0
RingBuf<uint8_t, BUFFER_SIZE> myBuffer;
myBuffer.push(ZERO);
```

note: candidate: bool RingBuf<ET, S, IT, BT>::push(const ET*) [with ET = unsigned char; unsigned int S = 24; IT = unsigned char; BT = short unsigned int]
Compilation error: call of overloaded 'push(int)' is ambiguous

I guess Zero does not count as an Integer. I tried defining a variable = 0; and putting just a zero in. 

Changing to: (works)
`RingBuf<int, BUFFER_SIZE> myBuffer;`

Changing to: (Does not work)
`RingBuf<int8_t, BUFFER_SIZE> myBuffer;`

Change to: (Works)
```
#define ZERO 0.0
RingBuf<float_t, BUFFER_SIZE> myBuffer;
```

**Comment by Koryphon** [comment]
Hello,

2 ways:

1 - ```#define ZERO (uint8_t)0```

2 - ```const uint8_t ZERO = 0;```

Best regards
