### ISSUE TITLE
Unable to use Library with atmelsam

### ISSUE THREAD

**Issue by f4814** [Locoduino/RingBuffer#2]
If I try to use the library on platformio with

    platform = atmelsam
    framework = arduino
    board = due

it fails with the following error: (It works on atmelavr though)

    src/master.cpp:12:1: error: 'RingBuffer' is not a template
    RingBuffer<char, 255> Test;

**Comment by Koryphon** [comment]
Hello,

Could you attach the source file master.cpp ?

**Comment by fixbravo** [comment]
Hello,

I have the same error when using a DUE ATSAM3X8E. I don't have any error when using the same code on a mega 2560.

Here is the error on the DUE :


```
test:5:1: error: 'RingBuffer' is not a template

 RingBuffer<float, 48> h;
```


And the code :

```
#include <RingBuffer.h>
//https://github.com/Locoduino/RingBuffer

RingBuffer<float, 48> h;

void setup() {
  // put your setup code here, to run once:

}

void loop() {
  // put your main code here, to run repeatedly:
  h.push(3.14);
}
```

**Comment by Koryphon** [comment]
Hello,

Thanks for the report.

There is a name conflict with a RingBuffer which is used internally in the ARM Arduino core. I'll fix it by changing the name to RingBuf but I have to check if the library can keep its current name. 

I try to do that today

**Comment by Koryphon** [comment]
Hello,

The conflict has been resolved in version 1.0.2 which should be available in the library manager in a few  hours (I hope).

Thanks for your contribution

**Comment by fixbravo** [comment]
Hello,

Thank you for fixing the issue ! I think there is another library named RingBuf referenced in the Arduino IDE but I guess there is no reason to use both.

Thanks again

**Comment by Koryphon** [comment]
You are welcome.
