### ISSUE TITLE
Make mReadIndex Value Transparent

### ISSUE THREAD

**Issue by PowerBroker2** [Locoduino/RingBuffer#3]
This is a super cool lib and thanks for putting it together.

I'd like to be able to figure out what the `mReadIndex` value is during sketch execution, but it's a private member. It would be super cool if you would add an access function to `mReadIndex` or add a `peek()` function that acts as `pop()` does, but doesn't remove the value read. If you'd like me to do a PR for this, I can do that, too.

**Comment by Koryphon** [comment]
Hello, this is provided by operator[]
Best regards
