### ISSUE TITLE
How to peek into buffer

### ISSUE THREAD

**Issue by firesurfer** [Locoduino/RingBuffer#4]
Hi, 
is there a way to nicely peek into the buffer without actually poping the data?

I would like to use this ringbuffer to parse a message protocol which has a length field. It would be nice if I could do something like this:

```
uint8_t size = 0;
if(buffer.peek(size))
{
   if(size >= buffer.size()) 
   {
        //Parse everything
   }
   else {
      // Wait until a full data package has been recieved
   }
} 
```

Thanks a lot!

**Comment by firesurfer** [comment]
Solved it by locally cloning the libary and adding a peek method

**Comment by Koryphon** [comment]
Hello, 

You have the operator[] to get data from the buffer without popping them. You code would be:
```
uint8_t currentSize = buffer.size();
if (currentSize > 0 && buffer[0] >= currentSize) {
    // parse everything
}
```

**Comment by firesurfer** [comment]
@Koryphon would you be willing to take a pull request which adds a peek method?

**Comment by Koryphon** [comment]
Hello,

Since this method would provide the data and return a bool specifying if a data is available so that it is simpler to use it, yes.

**Comment by firesurfer** [comment]
@Koryphon  see my PR #5
