### ISSUE TITLE
Incompatibility with Sdfat Library

### ISSUE THREAD

**Issue by glen-02** [Locoduino/RingBuffer#7]
Functions from RingBuf library dont work when i include this library: https://github.com/greiman/SdFat

**Comment by Koryphon** [comment]
Hello,

There is a RingBuf.h file in this library and a RingBuf class too. A workaround is to change the name of my library file to CircularBuf.h and change RingBuf to CircularBuf everywhere in the CircularBuf.h file.

Library developper should hide in namespace all classes which are used internally in the library to prevent name conflicts. But they doing not.

Best regards
